#!/usr/bin/env python3
"""Emit a static CUDA/C++ workload header from out/gpu_workload.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "out" / "gpu_workload.json"
DEFAULT_OUTPUT = ROOT / "gpu" / "generated" / "gpu_workload.h"
WORDLIST = ROOT / "data" / "bip39_english.txt"


def c_array(values: list[int], c_type: str, name: str, per_line: int = 12) -> list[str]:
    if not values:
        values = [0]
    lines = [f"ZENON_GPU_DEVICE_ARRAY {c_type} {name}[] = {{"]
    for index in range(0, len(values), per_line):
        chunk = values[index : index + per_line]
        suffix = "," if index + per_line < len(values) else ""
        lines.append("    " + ", ".join(str(value) for value in chunk) + suffix)
    lines.append("};")
    return lines


def pack_11bit_indices(indices: list[int]) -> bytes:
    bits = "".join(f"{index:011b}" for index in indices)
    if len(bits) % 8:
        raise ValueError("11-bit indices do not align to whole bytes")
    return int(bits, 2).to_bytes(len(bits) // 8, "big")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default=str(DEFAULT_INPUT))
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)
    if not input_path.is_absolute():
        input_path = ROOT / input_path
    if not output_path.is_absolute():
        output_path = ROOT / output_path

    workload = json.loads(input_path.read_text())
    words = WORDLIST.read_text().splitlines()
    if len(words) != 2048:
        raise SystemExit(f"expected 2048 BIP39 words, found {len(words)}")
    words_by_length = {
        int(length): [item["index"] for item in rows]
        for length, rows in workload["words_by_length"].items()
    }
    patterns = workload["length_patterns"]
    total_combinations = workload.get(
        "total_combinations", workload["total_exact_length_combinations"]
    )
    target_core = bytes.fromhex(workload["target_core_hex"])
    first_valid_core = bytes.fromhex(
        workload["validation_vectors"]["python_first_valid_core_hex"]
    )
    known_prefix_entropy = pack_11bit_indices(workload["known_indices"])
    known_prefix = (" ".join(workload["known_words"]) + " ").encode()

    word_offsets = []
    word_bytes = bytearray()
    for word in words:
        word_offsets.append(len(word_bytes))
        word_bytes.extend(word.encode())
    word_offsets.append(len(word_bytes))

    lines = [
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "// Generated by scripts/emit_cuda_workload_header.py. Do not hand edit.",
        "#ifdef __CUDACC__",
        "#define ZENON_GPU_DEVICE_ARRAY __device__ __constant__",
        "#define ZENON_GPU_DEVICE_INLINE __device__ inline",
        "#else",
        "#define ZENON_GPU_DEVICE_ARRAY static constexpr",
        "#define ZENON_GPU_DEVICE_INLINE inline",
        "#endif",
        "",
        "namespace zenon_gpu_workload {",
        "",
        f"static constexpr int kSearchModeAllWords = {1 if workload.get('search_mode') == 'all' else 0};",
        f"static constexpr uint64_t kTotalCombinations = {total_combinations}ULL;",
        f"static constexpr int kPlaintextBytes = {workload['plaintext_bytes']};",
        f"static constexpr int kPatternCount = {len(patterns)};",
        "",
    ]
    lines.extend(c_array(workload["known_indices"], "uint16_t", "kKnownIndices", 8))
    lines.append("")
    lines.extend(c_array(list(known_prefix), "uint8_t", "kKnownPrefixBytes", 16))
    lines.append(f"static constexpr int kKnownPrefixByteCount = {len(known_prefix)};")
    lines.append("")
    lines.extend(c_array(list(known_prefix_entropy), "uint8_t", "kKnownPrefixEntropyBytes", 11))
    lines.append("")
    lines.extend(c_array(list(target_core), "uint8_t", "kTargetCore", 20))
    lines.append("")
    lines.extend(c_array(list(first_valid_core), "uint8_t", "kFirstValidCore", 20))
    lines.append("")
    lines.extend(c_array(list(word_bytes), "uint8_t", "kWordChars", 24))
    lines.append("")
    lines.extend(c_array(word_offsets, "uint16_t", "kWordOffsets", 12))
    lines.append("")

    for length in sorted(words_by_length):
        lines.extend(c_array(words_by_length[length], "uint16_t", f"kWordsLen{length}"))
        lines.append(f"static constexpr int kWordsLen{length}Count = {len(words_by_length[length])};")
        lines.append("")

    pattern_lengths = [value for pattern in patterns for value in pattern["lengths"]]
    pattern_combinations = [pattern["combinations"] for pattern in patterns]
    pattern_starts = []
    start = 0
    for count in pattern_combinations:
        pattern_starts.append(start)
        start += count

    lines.extend(c_array(pattern_lengths, "uint8_t", "kPatternLengths", 16))
    lines.append("")
    lines.extend(c_array(pattern_combinations, "uint64_t", "kPatternCombinations", 4))
    lines.append("")
    lines.extend(c_array(pattern_starts, "uint64_t", "kPatternStarts", 4))
    lines.append("")
    lines.extend(
        [
            "ZENON_GPU_DEVICE_INLINE int count_for_length(int length) {",
            "    switch (length) {",
        ]
    )
    for length in sorted(words_by_length):
        lines.append(f"        case {length}: return kWordsLen{length}Count;")
    lines.extend(
        [
            "        default: return 0;",
            "    }",
            "}",
            "",
            "ZENON_GPU_DEVICE_INLINE const uint16_t* words_for_length(int length) {",
            "    switch (length) {",
        ]
    )
    for length in sorted(words_by_length):
        lines.append(f"        case {length}: return kWordsLen{length};")
    lines.extend(
        [
            "        default: return nullptr;",
            "    }",
            "}",
            "",
            "}  // namespace zenon_gpu_workload",
            "",
            "#undef ZENON_GPU_DEVICE_ARRAY",
            "#undef ZENON_GPU_DEVICE_INLINE",
            "",
        ]
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))
    print(f"Wrote {output_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
